version: '3'

networks:
  backend_network:
    driver: bridge
  frontend_network:
    driver: bridge


services:
  db:
    image: mysql:8

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 20s
      retries: 10

  api:
    build: ./node-api
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend_network
      - frontend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

  frontend:
    build: ./frontend
    expose:
      - 80
    ports:
      - 8080:80
    networks:
      - frontend_network
    depends_on:
      api:
        condition: service_healthy



volumes:
    db_data:

